name: build

on:
  push:
    branches:
      - master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install project Dependencies
        run: npm install

      - name: Patch astro config
        run: node patch-astro-config.js

      - name: Build
        run: npm run build

      - name: Deployment Setup
        run: |
          rm -rf .gitignore
          cd dist && touch .nojekyll

      - name: Deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: "dist"
          single-commit: true
          clean: true
